/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package group.project;


import java.io.IOException;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.Pane;


public class App extends Application {
	public static void main(String[] args) {
		System.out.println("Currently there are " +
				DAO.getAllStudents().size() + " student(s) in the database");
		Application.launch(args);
	}


	@Override
	public void start(Stage stage) throws IOException {
		Pane home = FXMLLoader.load(App.class.getClassLoader().getResource("Home.fxml"));
		Scene scene = new Scene(home, 892, 733);
		stage.setScene(scene);
		stage.show();
	}
}
